### ISSUE TITLE
How to use multi-gpu?

### ISSUE THREAD

**Issue by trikim** [facebookresearch/multigrain#3]
Excuse me, could you tell me how to use multi-gpu when training or testing?

**Comment by bermanmaxim** [comment]
The code already uses multi-gpu by default when training, using nn.DataParallel. See https://github.com/facebookresearch/multigrain/blob/a8e5bbfd5caeeaeb61631b63659a5381d1d3aed9/scripts/train.py#L99
When testing, one could wrap the model in an nn.DataParallel; this only works for square (cropped) inputs that can be batched, which is why it was not done. If you only want to use the model on cropped inputs, you can use nn.DataParallel; otherwise some more work has to be done for multi-gpu inference.

**Comment by trikim** [comment]
Thanks for your reply.
What's more, how long have you trained the multigrain model on imagenet dataset?
